name: Publish
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: The name of the release
        required: true

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    # if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

  build_frontend:
    env:
      PLUGIN_NAME: hdr-launcher
    runs-on: ubuntu-latest
    steps:
    - name: checkout version
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: npm install

    - run: npm run build

    - run: mkdir frontend
    - run: cp -r release frontend

    # upload built web files
    - name: Upload frontend artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend
        path: frontend
        
  build_the_plugin:
    runs-on: ubuntu-latest
    needs: build_frontend
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - name: checkout version
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      name: frontend

    - run: ls -lart
    - run: "rm -rf release && cp -r frontend/* ."
    - run: "ls -lart release/*"
    - run: |
        export PATH="$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin" \
        && cd switch \
        && cargo skyline build --release --features "updater no-npm"\
        && cd ..
      env:
        HOME: /root
        
    - run: mv switch/target/aarch64-skyline-switch/release/lib*.nro hdr-launcher.nro

    - run: |
        md5sum hdr-launcher.nro > checksum.txt

    # upload plugin
    - name: upload plugin
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "${{ github.event.inputs.release_name }}"
        files: |
          hdr-launcher.nro
          checksum.txt
        generate_release_notes: true
        draft: true