name: Publish
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: The name of the release
        required: true

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    # if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          #APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          #CSC_LINK: ${{ secrets.CSC_LINK }}
          #CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux

  build_the_plugin:
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - name: checkout version
      uses: actions/checkout@v2
    - name: Install Node.js and NPM
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - run: ls -lart
    - run: |
        export PATH="$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin" \
        && cd switch \
        && cargo skyline build --release --features "updater"\
        && cd ..
      env:
        HOME: /root
        
    - run: mv switch/target/aarch64-skyline-switch/release/lib*.nro hdr-launcher.nro

    - run: |
        md5sum hdr-launcher.nro > checksum.txt

    # upload asset
    - name: Upload plugin to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: 'hdr-launcher.nro'
        prerelease: false
        file_glob: true
        asset_name: plugin
        release_name: "${{ github.event.inputs.release_name }}"
        tag: ${{github.ref_name}}
        overwrite: true
        body: Automatic build of hdr-launcher-react

    # upload asset
    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: 'checksum.txt'
        prerelease: false
        file_glob: true
        asset_name: checksum
        release_name: "${{ github.event.inputs.release_name }}"
        tag: ${{github.ref_name}}
        overwrite: true
        body: Automatic build of hdr-launcher-react